services:
  user-service:
    build:
      context: .
    image: invenlore/invenlore-user-service
    container_name: invenlore-user-service
    hostname: invenlore-user-service
    networks:
      - invenlore-network
    ports:
      - 80:80
      - 8080:8080
    environment:
      - APP_ENV=dev
      - APP_LOG_LEVEL=DEBUG
      - GRPC_PORT=8080
      - HEALTH_PORT=80
      - MONGO_URI=mongodb://user:password@ip:port
      - MONGO_DATABASE_NAME=invenlore-user-service-db
      - MONGO_OPERATION_TIMEOUT=10s
    deploy:
      restart_policy:
        condition: on-failure

networks:
  invenlore-network:
    external: true
