services:
  user-service:
    build:
      context: .
    image: invenlore/invenlore-user-service
    networks:
      - invenlore-network
    ports:
      - "80"
      - "8080"
    environment:
      - APP_ENV=dev
      - APP_LOG_LEVEL=DEBUG
      - GRPC_PORT=8080
      - HEALTH_PORT=80
      - MONGO_URI=mongodb://root:rootpass@mongodb:27017/?authSource=admin&directConnection=true
      - MONGO_DATABASE_NAME=invenlore-user-service-db
      - MONGO_HEALTHCHECK_TIMEOUT=2s
      - MONGO_HEALTHCHECK_INTERVAL=10s
      - MONGO_OPERATION_TIMEOUT=10s
      - MONGO_MIGRATION_TIMEOUT=1m
    depends_on:
      mongodb:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:8.2.3
    container_name: invenlore-user-service-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: invenlore-user-service-db
    volumes:
      - mongo_data:/data/db
    networks:
      - invenlore-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u root -p rootpass --authenticationDatabase admin --eval \"db.adminCommand('ping').ok\" | grep 1 >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 20

networks:
  invenlore-network:
    external: true

volumes:
  mongo_data:
    name: invenlore-user-service-mongo_data
