services:
  user-service:
    build:
      context: .
    image: invenlore/invenlore-user-service:master
    container_name: invenlore-user-service
    hostname: invenlore-user-service
    networks:
      - invenlore-network
    ports:
      - 80:80
      - 8081:8081
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - USER_SERVICE_ENDPOINT=invenlore-user-service:8081
    deploy:
      restart_policy:
        condition: on-failure

networks:
  invenlore-network:
    external: true
